common/models/Client.php
<?php

namespace common\models;

use common\components\cashback\models\CashbackCustomer;
use common\components\cashback\models\CashbackStat;
use common\models\queries\ClientQuery;
use Yii;
use yii\base\InvalidArgumentException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Exception;
use yii\helpers\ArrayHelper;
use yii\web\Cookie;

/**
 * This is the model class for table "{{%client}}".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $token
 * @property string $secret
 * @property string $ip
 * @property string $extension_id
 * @property string $user_agent
 * @property integer $created_at
 * @property integer $last_online_at
 * @property bool $secure public read-only property of $_secure
 *
 * @property User $user
 * @property CashbackCustomer[] $cashbackCustomers
 * @property CashbackStat[] $cashbackStats
 * @method void touch(string $attribute)
 */
class Client extends ActiveRecord
{
    const TOKEN_LENGTH = 32;
    /**
     * @var bool secure marker.
     * If client was found only by token - false, if with secret - true
     */
    private $_secure = true;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%client}}';
    }

    /**
     * @inheritdoc
     * @return ClientQuery|\yii\db\ActiveQuery
     */
    public static function find()
    {
        return Yii::createObject(ClientQuery::class, [get_called_class()]);
    }

    public static function getClientByCookies()
    {
        $clientToken = Yii::$app->request->cookies->getValue('client_token', false);
        $clientSecret = Yii::$app->request->cookies->getValue('client_secret', false);
        return static::getClient($clientToken, $clientSecret);
    }

    public static function getClient($clientToken = null, $clientSecret = null)
    {
        if($clientToken && strlen($clientToken) == static::TOKEN_LENGTH){
            if($clientSecret){
                $client = static::findOne(['token' => $clientToken, 'secret' => $clientSecret]);
                return $client;
            }
            $client = static::findOne(['token' => $clientToken]);
            if($client) $client->setSecure(false);
            return $client;
        }
        return null;
    }

    /**
     * Sets the _secure
     * @param bool $value the _secure
     * @return $this
     */
    private function setSecure(bool $value = true)
    {
        $this->_secure = $value;

        return $this;
    }

    public static function getClientByUser()
    {
        if (Yii::$app->user->isGuest) return null;
        $client = static::findOne(['user_id' => Yii::$app->user->id]);
        return $client ?: static::newRecord([
                'ip' => Yii::$app->request->userIP,
                'user_agent' => Yii::$app->request->userAgent,
                'user_id' => Yii::$app->user->id
            ]);
    }

    /**
     * Create new Client record
     * @param array|null $params
     * @param bool $cookies save token and secret in cookies
     * @return Client
     * @throws Exception
     */
    public static function newRecord($params = null, bool $cookies = false)
    {
        $client = new static($params);
        $client->token = $client->generateUniqueRandomString('token', static::TOKEN_LENGTH);
        $client->secret = Yii::$app->getSecurity()->generateRandomString(8);
        if ($client->save()) {
            if($cookies){
                static::addClientCookies($client);
            }
            return $client;
        }
        throw new Exception('Can\'t create new Client record');
    }

    public function generateUniqueRandomString($attribute, $length = 32)
    {
        $randomString = str_replace(['_', '-'], '0', strtolower(Yii::$app->getSecurity()->generateRandomString($length)));

        if (!$this->findOne([$attribute => $randomString]))
            return $randomString;
        else
            return $this->generateUniqueRandomString($attribute, $length);
    }

    /**
     * Save in cookies token and secret if secure
     * @param Client|array|string $client
     */
    public static function addClientCookies($client)
    {
        $clientToken = null;
        $clientSecret = null;
        if($client instanceof Client){
            $clientToken = $client->token;
            if($client->secure){
                $clientSecret = $client->secret;
            }
        }elseif(ArrayHelper::isAssociative($client) && isset($client['token'])){
            $clientToken = $client['token'];
            if(isset($client['secret'])){
                $clientSecret = $client['secret'];
            }
        }elseif (is_string($client) && strlen($client) == static::TOKEN_LENGTH){//Only token
            $clientToken = $client;
        }else{
            throw new InvalidArgumentException('Invalid type of param client. Available: Array, String, ' . self::className());
        }
        if($clientToken){
            Yii::$app->response->cookies->add(new Cookie([
                'name' => 'client_token',
                'value' => $clientToken,
                'expire' => time() + 30 * 24 * 60 *60,
            ]));
            if($clientSecret){
                Yii::$app->response->cookies->add(new Cookie([
                    'name' => 'client_secret',
                    'value' => $clientSecret,
                    'expire' => time() + 30 * 24 * 60 *60,
                ]));
            }else{
                Yii::$app->response->cookies->remove('client_secret');
            }
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['token', 'secret'], 'required'],
            [['user_id'], 'integer'],
            [['token', 'extension_id'], 'string', 'length' => static::TOKEN_LENGTH],
            [['token'], 'unique'],
            [['secret'], 'string', 'length' => 8],
            [['ip'], 'string', 'max' => 15],
            [['user_agent'], 'string', 'max' => 256],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'last_online_at'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'token' => 'Token',
            'secret' => 'Secret',
            'ip' => 'Ip',
            'extension_id' => 'Extension ID',
            'user_agent' => 'User Agent',
            'created_at' => 'Created At',
            'last_online_at' => 'Last Online At',
        ];
    }

    /**
     * @return \common\models\queries\UserQuery|\yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    /**
     * @return \common\models\queries\UserQuery|\yii\db\ActiveQuery
     */
    public function getCashbackStats()
    {
        return $this->hasMany(CashbackStat::class, ['customer_id' => 'customer_id'])->via('cashbackCustomers');
    }

    /**
     * @return \common\models\queries\UserQuery|\yii\db\ActiveQuery
     */
    public function getCashbackCustomers()
    {
        return $this->hasMany(CashbackCustomer::class, ['client_token' => 'token']);
    }

    /**
     * Gets the _secure
     * @return bool
     */
    public function getSecure()
    {
        return $this->_secure;
    }
}

backend/controllers/ClientController.php
<?php

namespace backend\controllers;

use common\models\Exchange;
use common\models\Transfer;
use common\models\UserCurrency;
use common\models\WithdrawTransfer;
use Yii;
use common\models\Client;
use backend\models\search\ClientSearch;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\web\View;

/**
 * ClientController implements the CRUD actions for Client model.
 */
class ClientController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Client models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new \backend\models\search\ClientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Client model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Displays a single Client model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionExchange($id)
    {
		$dataProvider = new ActiveDataProvider([
			'query' => Exchange::find()->byUserCurrency(ArrayHelper::getColumn(UserCurrency::find()->select(['id'])->byUser(Yii::$app->user->id)->all(),'id'))->main()
		]);
		return $this->render('exchange', [
			'model' => $this->findModel($id),
			'dataProvider' => $dataProvider
		]);
    }

    /**
     * Displays a single Client model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionWithdraw($id)
    {
		$dataProvider = new ActiveDataProvider([
    		'query' => WithdrawTransfer::find()->byUserCurrency(ArrayHelper::getColumn(UserCurrency::find()->select(['id'])->byUser(Yii::$app->user->id)->all(),'id'))->main()
		]);
        return $this->render('withdraw', [
            'model' => $this->findModel($id),
			'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Creates a new Client model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Client();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Client model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Client model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Client model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Client the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Client::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/client/_data.php
<?php
/**
 * Created by PhpStorm.
 * User: Freelancer
 * Date: 09.05.2019
 * Time: 01:19:40
 * @var \common\models\Transfer $model
 */

?>
<?=\backend\components\DataTreeHelper::renderTree($model->data)?>

backend/views/client/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Client */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="client-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <?= $form->field($model, 'token')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'secret')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'ip')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'extension_id')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'user_agent')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/client/_info.php
<?php
/**
 * Created by PhpStorm.
 * User: Freelancer
 * Date: 02.05.2019
 * Time: 19:58:35
 *
 */
/* @var $this yii\web\View */
/* @var $model common\models\Client */
?>
<div class="col-md-6">
	<?= \yii\widgets\DetailView::widget([
		'model' => $model,
		'attributes' => [
			'id',
			'user_id',
			'token',
			'secret',
			'ip',
			'extension_id',
			'user_agent',
			'created_at',
			'last_online_at',
		],
	]) ?>
</div>
<div class="col-md-6">
	<table class="table table-striped table-bordered detail-view">
		<thead>
		<tr>
			<th>Currency</th>
			<th>Amount</th>
		</tr>
		</thead>
		<tbody>
		<?php
		$userCurrencyDataProvider = new \yii\data\ActiveDataProvider([
			'query' => \common\models\UserCurrency::find()->byUser(Yii::$app->user->id),
			'pagination' => [
				'pageSize' => 50,
			],
		]);
		echo  \yii\widgets\ListView::widget([
			'dataProvider' => $userCurrencyDataProvider,
			'itemView' => 'user-currency/_item',
			'emptyText' => false,
			'summary' => '',
		]);
		?>
		</tbody>
	</table>
</div>

backend/views/client/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\ClientSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="client-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'token') ?>

    <?= $form->field($model, 'secret') ?>

    <?= $form->field($model, 'ip') ?>

    <?php // echo $form->field($model, 'extension_id') ?>

    <?php // echo $form->field($model, 'user_agent') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'last_online_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/client/_tabs.php
<?php
/**
 * Created by PhpStorm.
 * User: Freelancer
 * Date: 02.05.2019
 * Time: 19:45:51
 */

\yii\bootstrap\NavBar::begin([
	'options' => [
		'class' => 'nav-tabs nav-justified',
	],
]);
$menuItems = [
	['label' => 'Cashback', 'url' => ['/client/view', 'id' => $model->id]],
	['label' => 'Withdraw', 'url' => ['/client/withdraw', 'id' => $model->id]],
	['label' => 'Exchange', 'url' => ['/client/exchange', 'id' => $model->id]],
];
echo \yii\bootstrap\Nav::widget([
	'options' => ['class' => 'navbar-nav nav-tabs nav-justified'],
	'items' => $menuItems,
]);
\yii\bootstrap\NavBar::end();

backend/views/client/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Client */

$this->title = 'Create Client';
$this->params['breadcrumbs'][] = ['label' => 'Clients', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="client-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/client/exchange.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Client */
/* @var $dataProvider \yii\data\ActiveDataProvider */
/* @var $searchModel \common\models\WithdrawTransfer */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Clients', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
$view = $this;

?>
<div class="client-view row">
    <?=$this->render('_info',['model'=>$model])?>
    <div class="col-xs-12">
        <h2>Transfers</h2>
        <?=$this->render('_tabs',['model'=>$model])?>
    </div>
    <div class="col-xs-12">
		<?= \yii\grid\GridView::widget([
			'dataProvider' => $dataProvider,
			'columns' => [
				['class' => 'yii\grid\SerialColumn'],

				'id',
				'type',
				'status',
				[
                    'attribute' => 'amount',
                    'value' => function(\common\models\Exchange $data){
		                return Yii::$app->formatter->asCurrency($data->amount,$data->userCurrency->currency_code);
                    },
                    'header' => 'Exchange from',
                ],
				[
                    'attribute' => 'transferTo.amount',
                    'value' => function(\common\models\Exchange $data){
		                return Yii::$app->formatter->asCurrency($data->transferTo->amount,$data->transferTo->userCurrency->currency_code);
                    },
                    'header' => 'Exchange to',
                ],
				[
                    'attribute' => 'transferCommission.amount',
                    'value' => function(\common\models\Exchange $data){
		                return Yii::$app->formatter->asCurrency($data->transferCommission->amount,$data->transferCommission->userCurrency->currency_code);
                    },
                    'header' => 'Comission',
                ],
				'created_at:date',
				'updated_at:date',
				[
					'attribute' => 'data',
					'value' => function (\common\models\Exchange $data) use ($view){
						return $view->render('_data',['model'=>$data]);
					},
					'format' => 'html'
				],

				[
					'class' => \yii\grid\ActionColumn::className(),
					'buttons'=>[
						'reject'=> function ($url, $model){
		                    if($model->status != \common\models\Transfer::STATUS_REJECTED)
                                return Html::a('<span class="glyphicon glyphicon-remove"></span>',['/transfer/reject','id'=>$model['id']],['onclick'=>"return confirm('Are you shure you want to reject this transfer?')"]);
                        }
					],
					'template'=>'{view} {update} {delete} {reject}',
				],
			],
		]); ?>
    </div>

</div>

backend/views/client/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\ClientSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Clients';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="client-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Client', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
			[
				'attribute'=>'username',
				'value'=> function($model){
					return $model->user->username;
				},
				'format' => 'html',
			],
            'token',
//            'secret',
            'ip',
            //'extension_id',
//            'user_agent',
            'created_at:date',
            'last_online_at:date',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/client/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Client */

$this->title = 'Update Client: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Clients', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="client-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/client/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Client */
/* @var $dataProvider \yii\data\ActiveDataProvider */
/* @var $searchModel \common\models\WithdrawTransfer */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Clients', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="client-view row">
    <?=$this->render('_info',['model'=>$model])?>
    <div class="col-xs-12">
        <h2>Transfers</h2>
        <?=$this->render('_tabs',['model'=>$model])?>
    </div>
    <div class="col-xs-12">

    </div>

</div>

backend/views/client/withdraw.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Client */
/* @var $dataProvider \yii\data\ActiveDataProvider */
/* @var $searchModel \common\models\WithdrawTransfer */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Clients', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
$view = $this;
?>
<div class="client-view row">
    <?=$this->render('_info',['model'=>$model])?>
    <div class="col-xs-12">
        <h2>Transfers</h2>
        <?=$this->render('_tabs',['model'=>$model])?>
    </div>
    <div class="col-xs-12">
		<?= \yii\grid\GridView::widget([
			'dataProvider' => $dataProvider,
			'columns' => [
				['class' => 'yii\grid\SerialColumn'],

				'id',
				'userCurrency.currency_code',
				'type',
				'status',
				'amount',
				'paymentSystem.name',
				'created_at:date',
				'updated_at:date',
				[
                    'attribute' => 'data',
                    'value' => function (\common\models\WithdrawTransfer $data) use ($view){
						return $view->render('_data',['model'=>$data]);
                    },
                    'format' => 'html'
                ],

				[
					'class' => \yii\grid\ActionColumn::className(),
					'buttons' => [
						'reject' => function ($url, $model){
							if($model->status != \common\models\Transfer::STATUS_REJECTED && $model->status != \common\models\Transfer::STATUS_APPROVED)
								return Html::a('<span class="glyphicon glyphicon-remove"></span>',['/transfer/reject','id'=>$model['id']],['onclick'=>"return confirm('Are you shure you want to reject this transfer?')"]);
						},
						'approve' => function ($url, $model){
							if($model->status != \common\models\Transfer::STATUS_APPROVED && $model->status != \common\models\Transfer::STATUS_APPROVED)
								return Html::a('<span class="glyphicon glyphicon-ok"></span>',['/transfer/approve','id'=>$model['id']],['onclick'=>"return confirm('Are you shure you want to approve this transfer?')"]);
						}
					],
					'template'=>'{view} {update} {delete} {approve} {reject}',
				],
			],
		]); ?>
    </div>

</div>