common/models/DomainUnblock.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%domain_unblock}}".
 *
 * @property integer $id
 * @property string $name
 * @property string $pattern
 *
 * @property DomainUnblockProxy[] $domainUnblockProxies
 * @property Proxy[] $proxies
 * @deprecated
 */
class DomainUnblock extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%domain_unblock}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'pattern'], 'required'],
            [['name'], 'string', 'max' => 128],
            [['pattern'], 'string', 'max' => 512],
            [['name'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'pattern' => 'Pattern',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDomainUnblockProxies()
    {
        return $this->hasMany(DomainUnblockProxy::className(), ['domain_unblock_id' => 'id'])->inverseOf('domainUnblock');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProxies()
    {
        return $this->hasMany(Proxy::className(), ['id' => 'proxy_id'])->viaTable('{{%domain_unblock_proxy}}', ['domain_unblock_id' => 'id']);
    }
}

backend/controllers/DomainUnblockController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\DomainUnblock;
use backend\models\search\DomainUnblockSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * DomainUnblockController implements the CRUD actions for DomainUnblock model.
 */
class DomainUnblockController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
//            'access' => [
//                'class' => AccessControl::className(),
//                'rules' => [
//                    [
//                        'allow' => true,
//                        'roles' => ['@'],
//                    ],
//                ],
//            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all DomainUnblock models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DomainUnblockSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single DomainUnblock model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new DomainUnblock model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new DomainUnblock();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing DomainUnblock model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing DomainUnblock model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the DomainUnblock model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return DomainUnblock the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = DomainUnblock::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/domain-unblock/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\DomainUnblock */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="domain-unblock-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput() ?>

    <?= $form->field($model, 'pattern')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/domain-unblock/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\DomainUnblockSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="domain-unblock-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'pattern') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/domain-unblock/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\DomainUnblock */

$this->title = 'Create Domain Unblock';
$this->params['breadcrumbs'][] = ['label' => 'Domain Unblocks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="domain-unblock-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/domain-unblock/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\DomainUnblockSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Domain Unblocks';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="domain-unblock-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Domain Unblock', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'label' => 'Name',
                'attribute' => 'name',
                'value' => function (\common\models\DomainUnblock $model, $key, $index, $column) {
                    return \yii\bootstrap\Html::a($model->name, ['/domain-unblock/view', 'id' => $model->id]);
                },
                'format' => 'Html',
            ],
            'pattern',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/domain-unblock/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\DomainUnblock */

$this->title = 'Update Domain Unblock: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Domain Unblocks', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="domain-unblock-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/domain-unblock/view.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $model common\models\DomainUnblock */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Domain Unblocks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="domain-unblock-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'pattern',
            [
                'label' => 'Proxies',
                'value' => function (\common\models\DomainUnblock $model, $widget) {
                    $linkDataProvider = new \yii\data\ActiveDataProvider([
                        'query' => $model->getDomainUnblockProxies()
                    ]);
                    return ListView::widget([
                        'dataProvider' => $linkDataProvider,
                        'itemView' => 'domain-unblock-proxies/_item',
                        'emptyText' => false,
                        'summary' => '',
                    ]);
                },
                'format' => 'raw',
            ],
        ],
    ]) ?>
    <p>
        <?php Modal::begin([
            'header' => '<h2>Add Proxies</h2>',
            'toggleButton' => ['label' => 'Add Proxies', 'class' => 'btn btn-success'],
        ]);

        echo $this->render('/domain-unblock-proxy/_form-multi', [
            'model' => new \backend\models\forms\DomainUnblockProxyMultiForm(['domain_unblock_id' => $model->id]),
            'back' => \yii\helpers\Url::to(),
            'domain_unblock' => $model,
        ]);

        Modal::end();
        ?>
    </p>

</div>