backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use backend\models\search\BonusesSearch;
use backend\models\search\CashbackSearch;
use backend\models\search\DomainSearch;
use backend\models\search\ReviewSearch;
use backend\models\search\SiteImageSearch;
use backend\models\search\SiteTranslationSearch;
use backend\models\search\TranslateSearch;
use common\components\cashback\models\Cashback;
use common\models\forms\SiteInfoForm;
use common\models\SiteInfo;
use common\models\Translate;
use Yii;
use common\models\Site;
use backend\models\search\SiteSearch;
use yii\base\Model;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SiteController implements the CRUD actions for Site model.
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
//            'access' => [
//                'class' => AccessControl::className(),
//                'rules' => [
//                    [
//                        'allow' => true,
//                        'roles' => ['@'],
//                    ],
//                ],
//            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Site models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SiteSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Site model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Displays a single info Site model.
     * @param integer $id
     * @return mixed
     */
    public function actionTypeInfo($id)
    {
        return $this->render('type-info', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Site model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Site();
        $modelInfo = new SiteInfo();

        if ($model->load(Yii::$app->request->post()) && $modelInfo->load(Yii::$app->request->post()) && Model::validateMultiple([$model, $modelInfo])) {
            $model->save(false); // skip validation as model is already validated

            $modelInfo->id = $model->id; // no need for validation rule on user_id as you set it yourself
            $modelInfo->save(false);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'info' => $modelInfo,
            ]);
        }
    }

    /**
     * Updates an existing Site model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelInfo = SiteInfo::findOne($id);
        if(!$modelInfo){
            $modelInfo = new SiteInfo();
            $modelInfo->link('site', $model);
        }

        if ($model->load(Yii::$app->request->post()) && $modelInfo->load(Yii::$app->request->post()) && Model::validateMultiple([$model, $modelInfo])) {
            $model->save(false);
            $modelInfo->save(false);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'info' => $modelInfo,
            ]);
        }
    }

    /**
     * Deletes an existing Site model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Lists all Domains models of Site.
     * @param $id
     * @return string
     */
    public function actionDomains($id)
    {
        $model = $this->findModel($id);
        $searchModel = new DomainSearch();
        $dataProvider = $searchModel->search(ArrayHelper::merge(Yii::$app->request->queryParams, ['DomainSearch' => ['site_id' => $model->id]]));

        return $this->render('domains/index', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Translations models of Site.
     * @param $id
     * @return string
     */
    public function actionTranslations($id)
    {
        $model = $this->findModel($id);
		$translate = new Translate();

		if(isset(Yii::$app->request->post('Translate')['id']) && !empty(Yii::$app->request->post('Translate')['id'])){
			$translate = Translate::findOne(Yii::$app->request->post('Translate')['id']);
		}
		$translate->load(Yii::$app->request->post());

		if ($translate->validate()) {
			$translate->save();
		}
        return $this->render('translate/index', [
            'model' => $model,
        ]);
    }

	/**
	 * Displays a single Site model.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionReviews($id)
	{
		$model = $this->findModel($id);
		$modelInfo = SiteInfoForm::findOne($id);
		if(!$modelInfo){
			$modelInfo = new SiteInfoForm();
			$modelInfo->link('site', $model);
		}

		if ($modelInfo->load(Yii::$app->request->post()) && $modelInfo->validate()) {
			$modelInfo->save();
			return $this->redirect(['reviews', 'id' => $model->id]);
		} else {
			return $this->render('reviews', [
				'model' => $model,
				'info' => $modelInfo,
			]);
		}
	}

//    /**
//     * Lists all Reviews models of Site.
//     * @param $id
//     * @return string
//     */
//    public function actionReviews($id)
//    {
//        $model = $this->findModel($id);
//        $searchModel = new ReviewSearch();
//        $dataProvider = $searchModel->search(ArrayHelper::merge(Yii::$app->request->queryParams, ['ReviewSearch' => ['site_id' => $model->id]]));
//
//        return $this->render('reviews/index', [
//            'model' => $model,
//            'searchModel' => $searchModel,
//            'dataProvider' => $dataProvider,
//        ]);
//    }

    /**
     * Lists all Bonuses models of Site.
     * @param $id
     * @return string
     */
    public function actionBonuses($id)
    {
        $model = $this->findModel($id);
        $searchModel = new BonusesSearch();
        $dataProvider = $searchModel->search(ArrayHelper::merge(Yii::$app->request->queryParams, ['BonusesSearch' => ['site_id' => $model->id]]));

        return $this->render('bonuses/index', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all SiteImages models of Site.
     * @param $id
     * @return string
     */
    public function actionImages($id)
    {
        $model = $this->findModel($id);
        $searchModel = new SiteImageSearch();
        $dataProvider = $searchModel->search(ArrayHelper::merge(Yii::$app->request->queryParams, ['SiteImageSearch' => ['site_id' => $model->id]]));

        return $this->render('images/index', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Finds the Site model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Site the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Site::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use common\models\Domain;
use common\models\Link;
use common\models\Proxy;
use common\modules\away\link\MacrosLink;
use frontend\models\forms\UrlForm;
use frontend\models\search\SiteSearch;
use frontend\models\Site;
use Yii;
use yii\base\DynamicModel;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;

class SiteController extends \yii\web\Controller
{
    /**
     * @return string
     */
    public function actionCasino()
    {
        $userCountry = Yii::$app->request->getCountry() ?: 'gb';

        $searchModel = new SiteSearch();
        $dataProvider = $searchModel->search(ArrayHelper::merge(Yii::$app->request->queryParams, ['SiteSearch' => ['type' => Site::TYPE_CASINO, 'geo_code' => $userCountry]]));
        if (!$dataProvider->count) {
            $dataProvider = $searchModel->search(ArrayHelper::merge(Yii::$app->request->queryParams, ['SiteSearch' => ['type' => Site::TYPE_CASINO, 'geo_code' => 'gb']]));
        }
        if(Yii::$app->request->isAjax){
            return $this->renderAjax('_listView', [
                'dataProvider' => $dataProvider,
            ]);
        }
        return $this->render('casino', [
            'dataProvider' => $dataProvider,
            'geo_code' => $userCountry,
            'urlForm' => new UrlForm(),
        ]);
    }

    public function actionAccess($id = null, $domain = null)
    {
        if (!$id && !$domain) throw new NotFoundHttpException('The requested page does not exist.');

        $extension_id = Yii::$app->request->cookies->getValue('client_ext_id', Yii::$app->params['extension_id']);

        $response = ['list' => [], 'redirect_url' => null];
        $sites = [];
        if ($id) {
            $site = $this->findModel($id);
            $sites[] = $site;
            if (in_array($site->type, [Site::TYPE_BETTING, Site::TYPE_POKER, Site::TYPE_CASINO])) {
                $sites = ArrayHelper::merge($sites, Site::findAll(['type' => Site::TYPE_HIDDEN]));
            }
            foreach ($sites as $site) {
                /** @var Site $site */
                foreach ($site->domains as $domain) {
                    /** @var Domain $domain */
                    if ($domain->proxy_pattern && $domain->proxies) {
                        if ($domain->type == Domain::TYPE_MAIN && !$response['redirect_url']) $response['redirect_url'] = (string)Yii::createObject(MacrosLink::class, [$domain->direct_url]);
                        $domain_unblock_array = [
                            'name' => $domain->domain,
                            'type' => $site->type,
                            'pattern' => $domain->proxy_pattern,
                            'proxy' => $domain->getProxies()
                                ->select(["CONCAT(host,':', port) as address", "login", "password"])
                                ->where(['status' => Proxy::STATUS_ACTIVE])
                                ->asArray()->all(),
                        ];
                        //$domain_unblock_array['proxy'] = ArrayHelper::getColumn($domain->proxies, 'fullAddress');
                        $response['list'][] = $domain_unblock_array;
                    }
                }
            }
        } elseif ($domain) {
            $response['redirect_url'] = 'http://' . $domain . '/';
            $response['list'][] = [
                'name' => $domain,
                'type' => Site::TYPE_OTHER,
                'pattern' => "shExpMatch(host, '{$domain}') || shExpMatch(host, '*.{$domain}')",
                'proxy' => Proxy::find()->select(["CONCAT(host,':', port) as address", "login", "password"])
                    ->where(['status' => Proxy::STATUS_ACTIVE, 'type' => Proxy::TYPE_PUBLIC])
                    ->asArray()->all(),
            ];
        }

        return $this->render('access', [
            'sites' => $response,
            'extension_id' => $extension_id,
        ]);
    }

    public function actionCheck()
    {
        $urlForm = new UrlForm();
        if ($urlForm->load(Yii::$app->request->queryParams) && $urlForm->validate()) {
            $site = $urlForm->find();
            if ($site) return $this->redirect(['access', 'id' => $site->id]);
            else return $this->redirect(['access', 'domain' => $urlForm->url]);
        } else {
            return $this->redirect(['index']);
        }
    }

    public function actionIndex()
    {
        $userCountry = Yii::$app->request->getCountry() ?: 'gb';

        $searchModel = new SiteSearch();
        $dataProvider = $searchModel->search(ArrayHelper::merge(Yii::$app->request->queryParams, ['SiteSearch' => ['type' => Site::TYPE_OTHER, 'geo_code' => $userCountry]]));
        if (!$dataProvider->count) {
            $dataProvider = $searchModel->search(ArrayHelper::merge(Yii::$app->request->queryParams, ['SiteSearch' => ['type' => Site::TYPE_OTHER, 'geo_code' => 'gb']]));
        }

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'geo_code' => $userCountry,
            'urlForm' => new UrlForm(),
        ]);
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id)
        ]);
    }

	public function actionReview($id)
	{
		return $this->render('reviews',[
			'model' => $this->findModel($id)
		]);
    }

    public function actionSettings()
    {
        return $this->render('settings', [
            'extension_id' => Yii::$app->request->cookies->getValue('ueid', Yii::$app->params['extension_id'])
        ]);
    }

    public function actionAjaxSiteList($q = null)
    {
        //TODO: Refactor + make search model
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = ['results' => []];
        if (!is_null($q)) {
            $sites = Site::find()
                ->select(['site.id AS id', 'site.name AS name', 'domain.domain AS domain', 'site_image.src AS img_src'])
                ->joinWith([
                    'domains' => function ($query) use ($q) {
                        /** @var $query ActiveQuery */
                        $query->onCondition(['like', 'domain.domain', $q])
                            ->limit(1);
                    },
                ], false)
                ->joinWith([
                    'siteImages' => function ($query) {
                        /** @var $query ActiveQuery */
                        $query->onCondition(['site_image.type' => 'logo'])
                            ->limit(1);
                    },
                ], false)
                ->where(['site.status' => Site::STATUS_ACTIVE])
                ->andWhere(['or', ['like', 'site.name', $q], ['like', 'site.aliases', $q]])
                ->groupBy('site.id')
                ->limit(20)
                ->asArray()->all();
            $out['results'] = array_values($sites);

            $model = DynamicModel::validateData(['url'=>$q], [
                ['url', 'url', 'defaultScheme' => 'http'],
                ['url', 'filter', 'filter' => function ($value) {
                    $parts = explode('/', $value, 4);
                    $domain = $parts[2];
                    return $domain;
                }]
            ]);

            if (!$model->hasErrors()) {
                array_unshift($out['results'], ['id' => $q, 'name' => 'Custom domain: ' . $q, 'domain' => $q, 'img_src' => null]);
            }

        }
        return $out;
    }


    /**
     * Finds the Site model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Site the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Site::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/site/_bonuses.php
<?php
/* @var \frontend\models\Site $model */
?>
<div class="bonus-list">
    <h2><?= Yii::t('front', 'Available bonuses:') ?></h2>
    <?php
    $bonuses = [
        ['title' => 'Bonus type'],
        ['title' => 'Bonus type'],
        ['title' => 'Bonus type'],
    ];
    foreach ($bonuses as $key => $bonus) { ?>
        <div class="bonus-block <?= $model->rank ?>">
            <div class="bonus-text"><?= $bonus['title'] ?></div>
            <button data-toggle="modal" data-target="<?= '#bonus-' . $key ?>" class="bonus-button">Activate</button>
            <div class="inset-border"></div>
        </div>
    <?php } ?>

</div>

frontend/views/site/_bonuses_modal.php
<?php
use yii\bootstrap\Modal;
use yii\helpers\Html;
/* @var \frontend\models\Site $model */

$bonuses = [
    ['title' => 'Bonus type'],
    ['title' => 'Bonus type'],
    ['title' => 'Bonus type'],
];


$favicon = $model->getSiteImages()->type('logo')->one()->src ?? '/img/frank.png';

foreach ($bonuses as $key => $bonus) {

    Modal::begin([
        'id' => 'bonus-' . $key,
        'header' => '<nav id="w2" class="navbar-static-top navbar-inverse navbar" role="navigation">
    <div class="navbar-header"><a class="navbar-brand" href="/"><img src="' . $favicon . '"></a></div>
    <div class="collapse navbar-collapse ">
        <ul id="" class="navbar-nav nav">
            <li><h4>Type of bonus</h4></li>
            <li><h6>05.06.2017–05.06.2018</h6></li>
        </ul>
    </div>
</nav>',
        'footer' => '',
        'size' => 'modal-sm',
        'options' => ['class' => 'fade modal in bonus-modal']
    ]);
    ?>


    <div class="bonus-block">
        <p>Some AWESOME TEXT</p>
        <button class="btn btn-login"><?= Yii::t('front', 'Get it') ?></button>
    </div>
    <?php Modal::end() ?>
<?php } ?>

frontend/views/site/_carousel.php
<?php
use yii\bootstrap\Carousel;
use yii\helpers\Html;

/**
 * @var \yii\web\View $this
 * @var \frontend\models\Site|null $model
 * @var \frontend\models\Site[]|null $models
 * @var \yii\data\ActiveDataProvider|null $dataProvider
 */

if(!isset($carouselItems))
	$carouselItems = [];
$carouselCount = 3;
$models = [];
if(isset($dataProvider))
	$models = $dataProvider->getModels();
elseif(isset($model))
	$models = [$model];
foreach ($models as $model) {
	if (0 > --$carouselCount) break;
	$promoText = explode('|', $model->getPromoText(Yii::$app->request->getCountry() ?: 'gb') ?: '');

    $promoSrc = $model->getSiteImages()->type('promo')->one()->src ?? '/img/header-img.png';

	$carouselItems[] = [
        'content' => Html::a("<div class=\"banner\" style=\"background-image: url('" . $promoSrc . "')\">
                            <div class=\"container img-text\">
                                <span class=\"text top\">" . (@$promoText[0] ?: '') . "</span>
                                <span class=\"text center\">" . (@$promoText[1] ?: '') . "</span>
                                <span class=\"text bottom\">" . (@$promoText[2] ?: '') . "</span>
                                <span onclick=\"window.location.href='" . \yii\helpers\Url::to(['site/access', 'id' => $model->id]) . "';\" class=\"link play\">" . Yii::t('front', 'Play!') . "</span>
                                <div class=\"rating-box\"><span class=\"rating " . $model->rank . "\">" . Yii::$app->formatter->asDecimal($model->rating, 1) . "</span></div>
                            </div>  
                        </div>", ['site/view', 'id' => $model->id])
	];
};
echo Carousel::widget([
	'items' => $carouselItems,
	'options' => ['class' => 'carousel slide'],
	'controls' => ['<span><img src="/img/arrow-left.png"></span>', '<span><img src="/img/arrow-right.png"></span>'],
	'showIndicators' => false,
]); ?>

frontend/views/site/_item.php
<?php
use frontend\models\Site;

/* @var $this yii\web\View */
/* @var $model \frontend\models\Site */

$favicon = $model->getSiteImages()->type('logo')->one()->src ?? '/img/frank.png';
$screen = $model->getSiteImages()->type('preview')->one()->src ?? '/img/croup_13.png';

$url = ($model->type == Site::TYPE_CASINO ? '/site/view' : '/site/access');
?>
<div class="col-sm-6 col-lg-4 ">
    <div class="category-item <?= $model->type == Site::TYPE_OTHER ? 'silver' : $model->rank?>">
        <div class="item-padding">
            <a href="<?= \yii\helpers\Url::to([$url, 'id' => $model->id]) ?>">
                <div class="item-content">
                    <img class="icon" src="<?= $favicon ?>">
                    <h2 class="title"><?= $model->name ?></h2>
					<?php if($model->type !== Site::TYPE_OTHER) {?><h2 class="rating lato-regular"><?= Yii::$app->formatter->asDecimal($model->rating, 1) ?></h2><?php } ?>
                    <img class="screen" src="<?= $screen ?>">
                </div>
            </a>
			<?php if($model->type !== Site::TYPE_OTHER) {?>
            <a href="<?= \yii\helpers\Url::to(['site/access', 'id' => $model->id]) ?>">
                <div class="triangle <?= $model->rank ?>"><img src="/img/more.png"></div>
            </a>
            <?php } ?>
        </div>
    </div>
</div>

frontend/views/site/_search.php
<?php
use kartik\select2\Select2;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use yii\web\JsExpression;
use yii\web\View;

/* @var $this yii\web\View */
/* @var $geo_code string */
/* @var $urlForm \frontend\models\forms\UrlForm */

$url = \yii\helpers\Url::to(['/site/access']);
$formatJs = <<<JS
var formatRepo = function (repo) {
    if (repo.loading) {
        return repo.text;
    }
    var markup =
        '<div class="row">' + 
            '<div class="col-sm-12">' +
                (repo.img_src ? '<img src="' + repo.img_src + '" class="img-rounded" style="width:30px" />' : '') +
                '<b style="margin-left:5px">' + repo.name + '</b>' + 
            '</div>' +
        '</div>';
    return '<div style="overflow:hidden;">' + markup + '</div>';
};
var formatRepoSelection = function (repo) {
    if(repo.img_src) return '<img src="' + repo.img_src + '" class="img-rounded" style="width:16px" />' +
                '<b style="margin-left:5px">' + repo.name + '</b>';
    if(parseInt(repo.id)) return repo.name;
    
    return repo.id || repo.text;
}
JS;

// Register the formatting script
$this->registerJs($formatJs, View::POS_HEAD);

?>
<?php $form = ActiveForm::begin([
    'action' => ['/site/check'],
    'method' => 'get',
    'options' => ['class' => 'form-inline']
]); ?>
<div class="search">
	<?php // = $form->field($urlForm, 'url', ['template' => '{input}'])->textInput(['placeholder' => Yii::t('front', 'Enter site to access')]) ?>
    <?= $form->field($urlForm, 'url', ['template' => '{input}'])->widget(Select2::className(), [
        'value' =>  $urlForm->url,
        'initValueText' => $urlForm->url,
        'options' => ['placeholder' => 'Enter site to access'],
        'theme' => Select2::THEME_BOOTSTRAP,
        //'hideSearch' => true,
        //'readonly' => true,
        'pluginOptions' => [
            'allowClear' => false,
            'minimumInputLength' => 2,
            'ajax' => [
                'url' => \yii\helpers\Url::to(['/site/ajax-site-list']),
                'dataType' => 'json',
                'delay' => 250,
                'data' => new JsExpression('function(params) { return {q:params.term}; }'),
                'cache' => true
            ],
            'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
            'templateResult' => new JsExpression('formatRepo'),
            'templateSelection' => new JsExpression('formatRepoSelection'),
        ],
        'pluginEvents' => [
            "select2:selecting" => "function(event) { if(parseInt(event.params.args.data.id)) location.href = '{$url}?id=' + event.params.args.data.id }",
        ],
//        'addon' => [
//            'append' => [
//                'content' => Html::icon('search'),
//                'asButton' => true
//            ],
//        ]
    ]);
    ?>
    <div class="form-group">
		<?= Html::submitButton('<img src="/img/search.png">', ['class' => 'search-btn']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>

frontend/views/site/reviews.php
<?php
use yii\bootstrap\Carousel;

/* @var $this yii\web\View */
/* @var $model \frontend\models\Site */

$this->title = $model->name;
$promoText = explode('|', $model->getPromoText(Yii::$app->request->getCountry() ?: 'gb') ?: '');
/* @var $promo \common\models\SiteImage */
$promoSrc = $model->getSiteImages()->type('promo')->one()->src ?? '/img/header-img.png';
?>

<div class="banner" style="background-image: url('<?= $promoSrc ?>')">
    <div class="container img-text">
        <span class="text top"><?= (@$promoText[0] ?: '') ?></span>
        <span class="text center"><?= (@$promoText[1] ?: '') ?></span>
        <span class="text bottom"><?= (@$promoText[2] ?: '') ?></span>
		<?= \yii\bootstrap\Html::a('<span class="link play">' . Yii::t('front', 'Play!') . '</span>', ['/site/access', 'id' => $model->id]) ?>
        <div class="rating-box"><span class="rating <?= $model->rank ?>"><?= ($model->rating ?: '') ?></span></div>
    </div>
</div>
<div class="container info-container">

    <div class="site-category">
        <div class="row info-item-list">
            <div class="col-sm-6 col-lg-4 ">
                <div class="review-item gold">
                    <div class="border">
                        <div class="padding">
                            <div class="review-content">
                                <h3>User</h3>
                                <p>texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext<br/>
                                    texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext<br/>
                                    texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext<br/>
                                    texttexttexttext<br/>
                                    texttexttexttexttexttexttexttext<br/>
                                    texttexttexttexttexttexttexttext</p>
                                <div class="review-rating">5</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-lg-4 ">
                <div class="review-item silver">
                    <div class="border">
                        <div class="padding">

                            <div class="review-content">
                            <h3>User</h3>
                            <p>texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext<br/>
                                texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext<br/>
                                texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext<br/>
                                texttexttexttext<br/>
                                texttexttexttexttexttexttexttext<br/>
                                texttexttexttexttexttexttexttext</p>
                            <div class="review-rating">5</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-lg-4 ">

                <div class="review-item bronze">
                    <div class="border">
                        <div class="padding">

                            <div class="review-content">
                            <h3>User</h3>
                            <p>texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext<br/>
                                texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext<br/>
                                texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext<br/>
                                texttexttexttext<br/>
                                texttexttexttexttexttexttexttext<br/>
                                texttexttexttexttexttexttexttext</p>
                            <div class="review-rating">5</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <?=$this->render('_bonuses_modal',['model'=>$model])?>


</div>